apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: my-test-repo
  name: bogus-name
  description: Just a repo for testing
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
