openapi: 3.0.0
info:
  title: My Test Repo rename
  description: some bogus test repo
  version: 1.0.0
  x-cortex-git:
    github:
      repository: hannavigil-test-org/my-test-repo
  x-cortex-tag: my-test-repo
  x-cortex-link:
  - url: http://github.com/hannavigil-test-org/my-test-repo
    name: Github Repository
    type: documentation
  x-cortex-owners:
  - type: EMAIL
    email: hanna.vigil@cortex.io
